#-------------------------------
# Site Settings
title: ì´ì½”ë…¸ë¯¸ ê°€ì´ë“œ
description: ì´ ë¸”ë¡œê·¸ëŠ” ê¸ˆìœµ, ì£¼ì‹, íˆ¬ì, ë¶€ë™ì‚°, ëŒ€ì¶œ, ì°½ì—… ë“± ê²½ì œ ì „ë°˜ì— ê´€í•œ ì •ë³´ë¥¼ ì‰½ê³  ëª…í™•í•˜ê²Œ ì œê³µí•˜ëŠ” ê³µê°„ì…ë‹ˆë‹¤.
color_scheme: light # You have the option to choose between three modes: auto, light, and dark. The default mode is set to auto, which means that the color scheme will automatically adapt based on your operating system settings. This way, you can enjoy a personalized experience without having to manually switch between light and dark modes.


#-------------------------------
# Global Cover
global_cover:
  enable: true
  homepage_image: "images/economy.guide_Banner.webp" # This line allows you to add a beautiful image at the top of your site, creating an eye-catching visual element that enhances the overall appearance and appeal.


#-------------------------------
# Breadcrumbs
breadcrumbs:
  enable: true # This line of code enables you to easily incorporate breadcrumbs into your website. By setting the "enable" parameter to "true", breadcrumbs will be enabled on your website, allowing users to easily track their navigation and find relevant information. Conversely, setting the parameter to "false" will disable the display of breadcrumbs, removing this navigation feature from your website.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'ğŸ  í™ˆ'
      url: '/'
    - title: 'âœï¸ í¬ìŠ¤íŠ¸'
      url: '/blog/'



#-------------------------------
# Author Settings
author:
  author_name: ì¤„ë¦¬ ì •
  author_role: ê¸ˆìœµ ì»¨ì„¤í„´íŠ¸
  author_bio: ğŸ“ˆ ê¸ˆìœµ ë° ê²½ì œ ì „ë¬¸ê°€ ğŸ’¡ ê¸ˆìœµ ì‹œì¥ íŠ¸ë Œë“œì™€ ì°½ì—…, íˆ¬ìì— ëŒ€í•œ ê¹Šì´ ìˆëŠ” ë¶„ì„ì„ ì œê³µí•©ë‹ˆë‹¤. ë…ìë“¤ì´ ê²½ì œì  ëª©í‘œë¥¼ ë‹¬ì„±í•  ìˆ˜ ìˆë„ë¡ ì‹¤ì§ˆì ì¸ ì¡°ì–¸ê³¼ ì •ë³´ë¥¼ ì „ë‹¬í•˜ëŠ” ê²ƒì„ ëª©í‘œë¡œ í•©ë‹ˆë‹¤.
  author_avatar: 'images/Julie_Jung.webp'
  cta_button_text: ë¬¸ì˜
  cta_button_link: '/contact/'


#-------------------------------
# Projects Settings
projects_settings:
  enable: false
  projects_title: Portfolio
  projects_description:


#-------------------------------
# Testimonials Settings
testimonials:
  enable: false
  testimonials_title: Testimonials
  testimonials_description:

testimonial_items:
  - name: "Albert Flores"
    image: "/images/client-1.jpg"
    designation: "Data Scientist"
    content : "The incredible attention to detail displayed by this team is commendable. Every aspect of our project, no matter how small, was handled with precision and care. The result is a product that reflects their commitment to excellence."

  - name: "Wade Warren"
    image: "/images/client-2.jpg"
    designation: "DevOps Engineer"
    content : "Working with this creative powerhouse was an enlightening experience. Their brilliance in design thinking and creative solutions brought our project to life in ways we hadn't imagined. The team's passion for innovation is truly infectious."

  - name: "Jenny Wilson"
    image: "/images/client-3.jpg"
    designation: "Systems Analyst"
    content : "This team proved to be efficient problem solvers throughout our project. When faced with challenges, they tackled them with creativity and resourcefulness. Their ability to overcome obstacles ensured a smooth and successful project delivery."


#-------------------------------
# Blog Section
blog_settings:
  enable: true
  blog_title: ìµœê·¼ í¬ìŠ¤íŠ¸
  blog_description:


#-------------------------------
# Videos Settings
videos_settings:
  enable: false
  videos_title: Videos
  videos_description:


#-------------------------------
# Gallery Section
gallery_settings:
  enable: false
  gallery_title: Gallery
  gallery_description:


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to our newsletter and weâ€™ll send you the emails of latest posts.
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Me # Add your button text


#-------------------------------
# Social Icons Settings
social:
- {icon: "fa-brands fa-facebook", name: "Facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}
- {icon: "fa-brands fa-tiktok", name: "Tiktok", link: "https://tiktok.com"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com"}
- {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
- {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
- {icon: "fa-brands fa-microsoft", name: "Microsoft", link: "https://microsoft.com"}
- {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", name: "Dribbble" link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/search?o=r&m=free


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your form_id
  description: ì´ ë¸”ë¡œê·¸ëŠ” ê¸ˆìœµ, íˆ¬ì, ë¶€ë™ì‚° ë° ì°½ì—…ê³¼ ê´€ë ¨ëœ ë‹¤ì–‘í•œ ì§ˆë¬¸ê³¼ ìƒë‹´ ìš”ì²­ì„ í™˜ì˜í•©ë‹ˆë‹¤. ë¬¸ì˜ ì–‘ì‹ì„ í†µí•´ ì–¸ì œë“ ì§€ ê¶ê¸ˆí•œ ì‚¬í•­ì„ ë³´ë‚´ì£¼ì‹œë©´, ìµœëŒ€í•œ ì‹ ì†í•˜ê²Œ ë‹µë³€ë“œë¦¬ê² ìŠµë‹ˆë‹¤. ì¬í…Œí¬, ì‹œì¥ ë¶„ì„, ê²½ì œ ë™í–¥ì— ëŒ€í•œ ë§ì¶¤í˜• ì¡°ì–¸ì„ ì›í•˜ì‹œë©´ ë¶€ë‹´ ì—†ì´ ì—°ë½ì£¼ì„¸ìš”.

# NOTE
# Priam theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
